name: chikankan
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  get_it: ^8.2.0
  cloud_firestore: ^6.0.3
  firebase_ai: ^3.4.0
  firebase_auth: ^6.1.1
  file_picker: ^8.0.0
  firebase_storage: ^13.0.3 
  image_picker: ^1.0.4 
  intl: ^0.18.0
  http: ^1.5.0
  huawei_location:
    path: ./huawei_location
  huawei_site: 6.5.1+303
  swipe_to: ^1.0.4
  url_launcher: ^6.2.2
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.65.0
  huawei_push: ^6.14.0+300
  latlong2: ^0.9.1
  flutter_map: ^8.2.2
  huawei_map:
    path: ./huawei_map
  permission_handler: ^12.0.1
  flutter_native_splash: ^2.4.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/applogo.png
    - assets/naive_bayes_model.json
    - .env

flutter_launcher_icons:
  android: true       # Generate for Android
  ios: true           # Generate for iOS
  image_path: "assets/applogo.png" # Path to your icon

flutter_native_splash:
  color: "#FFF4A4"
  image: assets/applogo-removebg-preview.png